### ISSUE TITLE
Verificacao de multiplas legendas

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [AdaptaBrasil/data_validate#117]
Verificar as legendas quando o usuario entregar uma legenda unica para cada indicador.

**Comment by MarioCarvalhoBr** [comment]
@pedro-andrade-inpe antes de começar essa issue, tenho algumas questões que preciso que resposa. Segue:
* Qual o nome da pasta o usuário deve entregar as multiplas legendas
* O que acontece se o usuário entregar um arquivo legenda.qml e uma pasta com as legendas?
* E se o usuário entregar uma pasta vazia? E um arquivo legenda.qml? 
* E se o usuário entregar somente uma pasta vazia de legendas/? 
* Vou supor que o nome da pasta de legendas seja *legendas/*. Dentro dessa pasta como os arquivos devem esta nomeados? {codigo_legenda.qml}? 
* O que acontece se o usuário não nomear as legendas de acordo com a quantidade de indicadores?
* O indicador nível 1 precisa de legenda?
* E se alguns o usuário entregar somente metade das legendas? 
* E se o usuário passar outros arquivos com outras extensões dentro da pasta de legendas? 
* O que acontece se uma legenda XXX_legenda.qml estiver corrompida e todas as outras funcionando? Acusamos erro somente para essa legenda?

**Comment by pedro-andrade-inpe** [comment]
> @pedro-andrade-inpe antes de começar essa issue, tenho algumas questões que preciso que resposa. Segue:
> 
> * Qual o nome da pasta o usuário deve entregar as multiplas legendas

Não tem pasta, entra junto com os demais arquivos.

> * O que acontece se o usuário entregar um arquivo legenda.qml e uma pasta com as legendas?

Se ele entregar os legenda.qml todos os demais qml entregues são desnecessários.

> * E se o usuário entregar uma pasta vazia? E um arquivo legenda.qml?

Não tem pasta.

> * E se o usuário entregar somente uma pasta vazia de legendas/?

Não tem pasta. Se não entregar nada, aplica-se a legenda default, todos os valores de zero a um.

> * Vou supor que o nome da pasta de legendas seja _legendas/_. Dentro dessa pasta como os arquivos devem esta nomeados? {codigo_legenda.qml}?

Os nomes dos arquivos sao <codigo>.qml, onde codigo é o codigo do indicador.

> * O que acontece se o usuário não nomear as legendas de acordo com a quantidade de indicadores?

Tudo o que nao estiver no padrao definido é arquivo desnecessário.

> * O indicador nível 1 precisa de legenda?

Só tem legenda os indicadores que tem dado. Lembre que indicadores de nivel 1 nao tem dado, e indicadores de nivel 2 podem ou nao ter dado.

> * E se alguns o usuário entregar somente metade das legendas?

Dizer quais estão faltando.

> * E se o usuário passar outros arquivos com outras extensões dentro da pasta de legendas?

Tudo arquivo desnecessário.

> * O que acontece se uma legenda XXX_legenda.qml estiver corrompida e todas as outras funcionando? Acusamos erro somente para essa legenda?

Sim.
