### ISSUE TITLE
Verificar diretórios obrigatórios

### ISSUE THREAD

**Issue by MarioCarvalhoBr** [AdaptaBrasil/data_validate#12]
Verificar se existem todos os diretórios obrigatórios descritos no PDF. Informar se faltam diretórios.

**Comment by MarioCarvalhoBr** [comment]
@pedro-andrade-inpe  resolvido na issue #39 
![Screenshot from 2024-02-29 11-58-59](https://github.com/AdaptaBrasil/data_validate/assets/12476879/ba0e2132-9960-4bb9-b27b-c759080bbe80)

close#12

**Comment by pedro-andrade-inpe** [comment]
Isso, mas faltam os demais arquivos

**Comment by pedro-andrade-inpe** [comment]
Os arquivos nao estao mais organizados por diretorios, assim essa issue é desnecessaria.
