### ISSUE TITLE
descricao.xlsx: relacao é opcional

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [AdaptaBrasil/data_validate#122]
A coluna relacao em descricao.xlsx é opcional. Quando for ausente, todos os indicadores terão valor 1 para a relação.

**Comment by MarioCarvalhoBr** [comment]
Correção proposta:
![image](https://github.com/AdaptaBrasil/data_validate/assets/12476879/6c12a454-d958-46dc-af16-3217ff4fd2c2)

**Comment by pedro-andrade-inpe** [comment]
Ok
