### ISSUE TITLE
descricao.xlsx: codigo deve ser sequencial

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [AdaptaBrasil/data_validate#124]
O Codigo devera ser sequencial começando de um: 1, 2, 3, 4...

**Comment by MarioCarvalhoBr** [comment]
No caso da imagem abaixo temos 3 erros: 

1.   Os códigos não comeram em 1. 
2.   Os códigos não estão sequênciais, pois o código `880000` é maior que os códigos subsequentes
3.   Os valores dos  códigos não são uma sequência de PA com razão 1

![image](https://github.com/AdaptaBrasil/data_validate/assets/12476879/10ed0223-9f7b-4fca-89a2-4ddbb1b9da0b)
