### ISSUE TITLE
Ordenar sub-arvores das relacoes entre indicadores

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [AdaptaBrasil/data_validate#157]
A mensagem de erro das relacoes entre indicadores precisa mostrar as sub-arvores ordenadas usando o menor pai até o maior pai.

![image](https://github.com/AdaptaBrasil/data_validate/assets/8777631/0c5cb9d7-a7ad-4da8-840c-6302cfe8c7bf)

Na figura acima, ao inves de comecar com 11->20, 11->21 deveria ser 1->2, 2->4, etc.

**Comment by MarioCarvalhoBr** [comment]
Ordenado!
