### ISSUE TITLE
erro quando os arquivos estiverem dentro de uma pasta

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [AdaptaBrasil/data_validate#164]
Quando os arquivos estiverem dentro de uma pasta zipada, ele fica dizendo que os arquivos nao foram encontrados. mostrar uma mensagem de erro dizendo que os arquivos nao podem estar dentro de uma pasta, tem que ser zipados diretamente.

**Comment by pedro-andrade-inpe** [comment]
Hoje a gente mostra uma mensagem de aviso, ela deve ser transformada em erro para a pessoa entender melhor o que aconteceu. Veja se consegue dizer que é uma pasta, a gente acaba chamando de arquivo na mensagem, isso pode confundir tambem.

![image](https://github.com/user-attachments/assets/97718a34-f7d5-484e-9820-2e6fa0dedb39)

**Comment by MarioCarvalhoBr** [comment]
Corrigido!
