### ISSUE TITLE
Verificar projeção dos dados espaciais

### ISSUE THREAD

**Issue by MarioCarvalhoBr** [AdaptaBrasil/data_validate#17]
Validar se os dados espaciais estão na projeção EPSG 3426 conforme especificado. Alertar se estiver em projeção diferente.

**Comment by pedro-andrade-inpe** [comment]
Isto será feito pela ferramenta de importação. Vou deixar aberto aqui por enquanto mas nao tem nada a ser feito pelo data validate.
