### ISSUE TITLE
legendas faltando ou sobrando

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [AdaptaBrasil/data_validate#171]
Quando o usuario passar varias legendas, verificar se existe uma relacao 1:1 entre legendas e codigos dos indicadores. Mostrar erro para cada legenda que estiver sobrando ou faltando.

**Comment by MarioCarvalhoBr** [comment]
Implementado na issue #177 

Faltando: 
![image](https://github.com/user-attachments/assets/30368082-3b5a-4905-a668-ec4b622d8917)

Sobrando: 
![image](https://github.com/user-attachments/assets/ad281623-04a0-43aa-9b98-5158304cf7f4)
