### ISSUE TITLE
Atualizar erros de valores errados em proporcionalidade e valores

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [AdaptaBrasil/data_validate#172]
Atualmente mostramos um erro para cada valor errado em valores e proporcionalidade. Mostrar apenas um erro por coluna, para nao ter muito erro. Quando tiver um unico erro, mostrar do jeito que ja funcionava:

```
valores.csv, linha 200: O valor que não é numero valido nem DI (Dado Indisponível) para a coluna 'XX".
```

Quando tiver mais de um erro, mostrar como se fosse um erro apenas:

```
valores.csv: XX valores que não são numero valido nem DI (Dado Indisponível) para a coluna 'XX", entre as linhas 25 e 32.
```

**Comment by MarioCarvalhoBr** [comment]
Conforme conversado,  o problema será resolvido apenas para valores.xlsx no momento.

**Comment by MarioCarvalhoBr** [comment]
Atualmente resolvido parcialmente para a planilha valores: 
![image](https://github.com/user-attachments/assets/a075fc05-a885-43a7-8a04-620843883bec)

**Comment by MarioCarvalhoBr** [comment]
![image](https://github.com/user-attachments/assets/3b613b9f-d554-455d-8259-d25a6ac80b55)
