### ISSUE TITLE
Indicador nível mais alto sem dados

### ISSUE THREAD

**Issue by MarioCarvalhoBr** [AdaptaBrasil/data_validate#18]
Verificar se o indicador no nível mais alto da hierarquia (nível 1) não possui colunas de dados associadas. Esse indicador serve apenas para agregar, não devendo ter valores.

**Comment by pedro-andrade-inpe** [comment]
É importante deixar claro aqui que o nivel 2 tambem nao tem dado, e o nível 3 pode ou nao ter dados. A ideia é que, dado um nível que tenha dado, todos os niveis inferiores tem que ter dado tambem.

**Comment by MarioCarvalhoBr** [comment]
Resolvido no PR #139
