### ISSUE TITLE
Analise duplicada de relacao entre descricao e valores

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [AdaptaBrasil/data_validate#192]
Existe uma analise duplicada da relacao entre descricao e valores.

Nste trecho:

![image](https://github.com/user-attachments/assets/1852459a-286f-4c09-8662-f035186b3a4b)

Esta mensagem de erro nao deveria existir. Cada mensagem em azul deve se referir a apenas uma issue, e essa deve se referir à issue #2 apenas. Estas mensagens de erro sao relativas à issue #59 que é resolvida mais pra frente.

Neste trecho abaixo:

![image](https://github.com/user-attachments/assets/516d9144-e0cc-493b-9641-057469202d08)

As duas primeiras linhas em azul se referem à #81 e esta correto, a ultima linha em azul se refere a #59 e deve ser atualizada.

**Comment by MarioCarvalhoBr** [comment]
Vou mostrar em cima apenas apenas as fora do padrão. 
Embaixo apenas as dentro do padrão e que são desnecessárias.
