### ISSUE TITLE
Fatores influenciadores somando zero

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [AdaptaBrasil/data_validate#206]
Existe uma possibilidade de os fatores influenciadores terem que ser zero. Quando os valores dos respectivos indicadores forem todos zero ou DI, pois neste caso nao tem como calcular os pesos dos fatores influenciadores. Adicionar esta verificacao.

**Comment by MarioCarvalhoBr** [comment]
![image](https://github.com/user-attachments/assets/3a829441-e825-4a40-b328-1d721ebe3a60)
