### ISSUE TITLE
Campos comecando com : na primeira e segunda linha de proporcionalidades 

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [AdaptaBrasil/data_validate#216]
Todos os campos que começarem com : na primeira e segunda linha de proporcionalidades devem gerar um erro. Apenas o padrao definido deve funcionar. O padrão é “[codigo]-[ano]-[cenario]” para ambas as linhas.

**Comment by MarioCarvalhoBr** [comment]
Exemplo da xorreção em valores, proporcionalidades (indicadores nível 1 e 2)
![image](https://github.com/user-attachments/assets/ee0bc9c3-8ccb-4e47-a5e6-cebdcc282476)

**Comment by pedro-andrade-inpe** [comment]
ótimo

**Comment by MarioCarvalhoBr** [comment]
@pedro-andrade-inpe PR aberto
