### ISSUE TITLE
Colocar separador de milhar/milhão nas quantidades no relatório

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [AdaptaBrasil/data_validate#229]
Colocar o separador de milhar/milhão nas quantidades no relatorio

![image](https://github.com/user-attachments/assets/1de81de8-96be-4430-b87a-0f3b225fcd09)

Por exemplo, acima deveria ser "54.902" e "67.751"

Fazer nos erros e warnings de "similares aos anteriores que foram omitidos" tambem

![image](https://github.com/user-attachments/assets/83425500-bd02-4c44-a66b-fe7a707a7874)

**Comment by MarioCarvalhoBr** [comment]
Quantidades no relatório

![image](https://github.com/user-attachments/assets/f7a829bd-31d9-469e-835f-1dd813d11c85)

**Comment by MarioCarvalhoBr** [comment]
Erros e warnings de "similares aos anteriores que foram omitidos" tambem

![image](https://github.com/user-attachments/assets/532cbc7f-f2f6-42f5-b4d7-bd39a0c1f0ff)

**Comment by pedro-andrade-inpe** [comment]
Ótimo!
