### ISSUE TITLE
Conferir valores dentro da legenda

### ISSUE THREAD

**Issue by MarioCarvalhoBr** [AdaptaBrasil/data_validate#23]
Validar se todos os valores dos indicadores estão dentro dos limites especificados na legenda. Informar quantos e quais estão fora.

**Comment by MarioCarvalhoBr** [comment]
Criar um arquivo de `legenda.xlsx` com os intervalos `min` e `max`

**Comment by pedro-andrade-inpe** [comment]
Duplicado #16
