### ISSUE TITLE
Descontinuidade na legenda

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [AdaptaBrasil/data_validate#231]
O erro:

```
legenda.qml: Arquivo está corrompido. Existe uma descontinuidade nos valores das
fatias da legenda.
```

esta ruim, mostrar qual foi a descontinuidade identificada.

**Comment by pedro-andrade-inpe** [comment]
Na verdade este erro esta ocorrendo quando existe uma sobreposicao nos intervalos das legendas, e nao uma descontinuidade. 

Descontinuidade: [0-10], [11-20]
Sobreposicao:  [0-10], [10-20]
Correto: [0-10], [10.01-20]

**Comment by pedro-andrade-inpe** [comment]
Lembrando que o padrao do adapta sao 2 casas decimais

**Comment by MarioCarvalhoBr** [comment]
@pedro-andrade-inpe isso foi corridido no PR #245 

Conforme a imagem abaixo, agora é mostrado os valores. 

![image](https://github.com/user-attachments/assets/f0cbfb73-d706-412e-a141-ca3888aefc9c)

**Comment by pedro-andrade-inpe** [comment]
Ótimo.
