### ISSUE TITLE
Multiplos erros na mesma legenda

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [AdaptaBrasil/data_validate#237]
Algumas legendas com problemas estao produzindo varios erros repetidos. Não mostrar erros repetidos.

![image](https://github.com/user-attachments/assets/0eea86ca-2c92-4e53-bea6-b7e5595adaaa)

Arquivo de teste:

[versao-6.zip](https://github.com/user-attachments/files/17347636/versao-6.zip)

**Comment by MarioCarvalhoBr** [comment]
Retirar a parte do "Arquivo corrompido" e reportar exatamente as sobreposição. 

Resolver em conjunto a issue @241
