### ISSUE TITLE
Casas decimais para valores

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [AdaptaBrasil/data_validate#28]
Ver o que fazer quando os valores tem muitas casas decimais. Uma ideia seria truncar para ter apenas duas casas decimais, mas precisamos avaliar melhor. Mas é bom ter alguma coisa automatizada para isso porque é muito trabalhoso para o usuario ficar alterando todos os dados.

**Comment by pedro-andrade-inpe** [comment]
Emitir apenas um warning por atributo, falando quantos valores tem mais de X casas decimais. Se mostrar um warning por valor fica muita mensagem. Verificar a especificacao se nao tem nada sobre isso e atualizar.

**Comment by pedro-andrade-inpe** [comment]
@MarioCarvalhoBr a verificação do numero de casas decimais é feita para a proporcionalidade, mas ela é feita tambem para os valores?

**Comment by MarioCarvalhoBr** [comment]
Falta fazer para valores.xlsx

**Comment by pedro-andrade-inpe** [comment]
No caso de valores sao apenas 2 casas decimais

**Comment by pedro-andrade-inpe** [comment]
Liberado para fazer esta tambem. Avisos para as colunas que tem pelo menos um valor com mais de 2 casas decimais.

**Comment by MarioCarvalhoBr** [comment]
Proporcionalidades: Até 3 casas decimais
Valores: Até 2

**Comment by MarioCarvalhoBr** [comment]
@pedro-andrade-inpe 

Feito para valores e para porporcionalidades
