### ISSUE TITLE
Valores fora do intervalo da legenda

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [AdaptaBrasil/data_validate#4]
Verificar se os valores dos indicadores estao fora do intervalo especificado na legenda (quando houver, ou fora do intervalo 0 a 1 se nao houver legenda especificada no dado). Contar quantos e quais sao os valores e os respectivos IDs que estao fora deste intervalo para mostrar na mensagem de erro.

**Comment by MarioCarvalhoBr** [comment]
@pedro-andrade-inpe  resolvido na issue #16 e na issue de múltiplas legendas #117

**Comment by pedro-andrade-inpe** [comment]
@MarioCarvalhoBr coloca algumas evidencias dos testes aqui por favor

**Comment by MarioCarvalhoBr** [comment]
Quando está fora da legenda passada: 
![image](https://github.com/user-attachments/assets/88818029-ff20-48e0-87c8-03bf3babb1a0)

Quando está fora do intervalo 0 e 1 (não passou legenda):
![image](https://github.com/user-attachments/assets/78db56c4-9ff5-4ba9-a504-8fb43c79bc9e)

Quando não passa as múltiplas legendas corretas:
![image](https://github.com/user-attachments/assets/c1b388b6-8d35-44b5-97b4-7fa065b8d761)

**Comment by MarioCarvalhoBr** [comment]
@pedro-andrade-inpe  está issue está resolvida. Vou subir uma aletração com mais um caso de teste.
