### ISSUE TITLE
Definicao de erros e warnings

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [AdaptaBrasil/data_validate#48]
Vamos padronizar o que são erros e o que são warnings. Um erro em uma determinada verificação significa que alguma verificação posterior **obrigatória** vai deixar de ser feita. Isso significa que, ao corrigir um determinado erro, novas verificações serão feitas e portanto novos erros ou warnings poderão acontecer. Um warning significa que, ao ser corrigida, nenhum erro ou warning futuro poderá ser gerado por causa disto. Por exemplo, um arquivo obrigatório que não exista impede que as verificações das informações dentro deste arquivo sejam feitas. Um outro exemplo: suponha um arquivo opcional que o usuário escreveu o nome errado. Ele vai receber um warning dizendo que existe um arquivo que esta fora da norma. Ao corrigir este warning pode gerar um erro, mas o erro ocorrerá porque um arquivo opcional não existia e passará a existir, e não por resolver o warning.

Toda vez que um erro aparecer, a ferramenta deverá deixar claro durante o processamento que alguma verificação posterior que ela não será realizada.  Por exemplo:

```
Verificando nomes dos arquivos
Arquivo cenarios.xls não encontrado
Verificando codigos html
Verificando titulos
Pulando verificação dos cenários [ou algo assim]
```

**Comment by MarioCarvalhoBr** [comment]
Resolvido no PR que resolveu a issue #65
