### ISSUE TITLE
Verificar propriedades de soma nos fatores influenciadores

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [AdaptaBrasil/data_validate#69]
Conversar com o time de indicadores se tem alguma propriedade na soma de fatores influenciadores. A soma deveria ser 100%?

**Comment by pedro-andrade-inpe** [comment]
Após conversa com Gustavo ficou definido que a soma deve ser 100%. Quando nao for 100% tem que gerar um erro.

**Comment by MarioCarvalhoBr** [comment]
Issue dentro do escopo e sendo resolvida atualmente. Não há dependências para a resolução da issue.

**Comment by MarioCarvalhoBr** [comment]
Essa issue diz respeito a planilha `proporcionalidades.xlsx`
