### ISSUE TITLE
Verificar dados faltantes

### ISSUE THREAD

**Issue by MarioCarvalhoBr** [AdaptaBrasil/data_validate#7]
Verificar se existem células em branco ou com valor "NA" nos arquivos de dados. Contar quantas células estão faltando em cada arquivo e relatar.

**Comment by pedro-andrade-inpe** [comment]
O ideal é relatar linha por linha

**Comment by pedro-andrade-inpe** [comment]
Isto já esta sendo verificado, certo @MarioCarvalhoBr ?
