### ISSUE TITLE
verificar arquivos de cenarios e anos

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [AdaptaBrasil/data_validate#81]
Verificar os arquivos de cenarios e anos: tipos das colunas, erros de portugues nas descricoes, se as descricoes terminam com ponto, e valores tem que ser unicos para nomes e simbolos.

**Comment by MarioCarvalhoBr** [comment]
- [X]  Erros de português nas descrições issue #24 
- [ ]  Tipos das colunas
- [ ]  Descrições terminam com ponto
- [ ]  Valores tem que ser unicos para nomes e simbolos.

**Comment by MarioCarvalhoBr** [comment]
- [ ]  Erros de português na coluna 'descricao' (referencia_temporal.xlsx)
- [ ]  Erros de português nas colunas 'nome' e 'descricao' (cenarios.xlsx)

![Screenshot from 2024-03-11 10-20-29](https://github.com/AdaptaBrasil/data_validate/assets/12476879/1d7c55b9-deb6-4c59-8dd5-6beb19f369e7)

**Comment by MarioCarvalhoBr** [comment]
Verificação de pontução em cenários (cenarios.xlsx)
![Screenshot from 2024-03-11 10-25-41](https://github.com/AdaptaBrasil/data_validate/assets/12476879/fa4e6d99-579b-403c-a7d7-4535175fdfff)

**Comment by MarioCarvalhoBr** [comment]
- [x]  Valores tem que ser unicos para nomes e simbolos  (cenarios.xlsx)

![Screenshot from 2024-03-11 13-13-38](https://github.com/AdaptaBrasil/data_validate/assets/12476879/5984a488-2005-4de3-880a-294af7c3e218)

**Comment by pedro-andrade-inpe** [comment]
@MarioCarvalhoBr "A coluna 'nome' não deve conter valores repetidos". O nosso usuário não sabe o que é valor único

**Comment by MarioCarvalhoBr** [comment]
- [ ] Valores tem que ser unicos para nomes e simbolos (referencia_temporal.xlsx)

![Screenshot from 2024-03-11 13-50-45](https://github.com/AdaptaBrasil/data_validate/assets/12476879/17bc868c-d952-4523-8e7f-03ebcc48013e)

**Comment by MarioCarvalhoBr** [comment]
- [x] Descrições terminam com ponto (cenarios.xlsx e referencia_temporal.xlsx)
![Screenshot from 2024-03-11 13-53-17](https://github.com/AdaptaBrasil/data_validate/assets/12476879/ca62ca50-88ba-4003-8721-4fdcde8af601)

**Comment by MarioCarvalhoBr** [comment]
@pedro-andrade-inpe  feito:

![Screenshot from 2024-03-11 14-28-00](https://github.com/AdaptaBrasil/data_validate/assets/12476879/58643ee1-8af6-41a9-bcf6-16bd2e612b9a)

**Comment by MarioCarvalhoBr** [comment]
Tipos das colunas: 

![Screenshot from 2024-03-11 14-55-46](https://github.com/AdaptaBrasil/data_validate/assets/12476879/8a1a2631-810e-4db1-9e79-325e8841f293)
