### ISSUE TITLE
Remover #$0D, #$0A (CR, LF) dos campos texto

### ISSUE THREAD

**Issue by assismauro** [AdaptaBrasil/data_validate#85]
Na tabela de descrição dos indicadores, identificar em todos os campos texto os caracteres CR e LF que estiverem no fim do texto.

Nos campos **nome** e **título**, identificar se ocorrerem em qualquer lugar do texto.

Gerar um warning em ambos os casos dizendo em que posição estavam os caracteres que foram identificados.

**Comment by MarioCarvalhoBr** [comment]
descrição.xlsx: 
     - Vetrificação CRLF em qualquer posição: nome_simples | nome_completo
     - Vetrificação CRLF no início e fim: codigo | nivel | nome_simples | nome_completo | unidade | desc_simples | desc_completa | cenario | relacao | fontes | meta

cenarios.xlsx:
       - Vetrificação CRLF no início e fim: nome, descricao
referencia_temporal.xlsx:
      - Vetrificação CRLF no início e fim: descricao
