### ISSUE TITLE
nova estrutura de arquivos

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [AdaptaBrasil/data_validate#89]
Refazer a estrutura de entrega dos arquivos dos setores estrategicos. Os dados entregues de um determinado setor estrategico deverão estar em apenas uma pasta, e os nomes dos arquivos são fixos e sem o numero no inicio. Ele serão: composicao.xlsx, descricao.xlsx, etc.

**Comment by MarioCarvalhoBr** [comment]
Estrutura antiga:
```
pasta_input │
                      ├── 3_cenarios_e_referencia_temporal
                      │   ├── cenarios.xlsx
                      │   └── referencia_temporal.xlsx
                      ├── 4_descricao
                      │   └── descricao.xlsx
                      ├── 5_composicao
                      │   └── composicao.xlsx
                      ├── 8_valores
                      │   └── valores.xlsx
                      └── 9_proporcionalidades
                          └── proporcionalidades.xlsx
```
Nova estrutura:
pasta_input │
                      │ ── cenarios.xlsx
                      │ ── referencia_temporal.xlsx
                      │ ── descricao.xlsx
                      │ ── composicao.xlsx
                      │ ── valores.xlsx
                      │ ── proporcionalidades.xlsx
```
